name: PrihVPN Full List Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download source configurations
        run: |
          curl -sLf "https://mifa.world/fast" -o raw.txt

      - name: Generate VPN profile
        run: |
          echo "#profile-update-interval: 1" > vpn.json
          echo "#profile-title: PrihVPN⚡" >> vpn.json
          echo "#announce: Все обновы в тг PrihsVPN!" >> vpn.json
          echo "" >> vpn.json

      - name: Filter and append proxies
        run: |
          tr -d '\r' < raw.txt | grep -E -i "(vless|trojan|ss|hysteria2)://" | grep -v "0.0.0.0" >> vpn.json || true

      - name: Clean up temporary files
        run: |
          rm -f raw.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add vpn.json
          git commit -m "Force Update (Mifa Only): $(date +'%H:%M:%S')" || echo "No changes to commit"
          git push origin main || git push --force
