name: mifa

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Это даёт права боту пушить файлы обратно

    steps:
      - uses: actions/checkout@v4

      - name: Run
        run: |
          curl -sL "https://mifa.world/fast" -o raw.txt || touch raw.txt

          echo "#profile-update-interval: 1" > vpn.json
          echo "#profile-title: PrihVPN⚡" >> vpn.json
          echo "#announce: Все обновы в тг PrihsVPN!" >> vpn.json
          echo "" >> vpn.json

          if [ -s raw.txt ]; then
            tr -d '\r' < raw.txt | grep -E -i "(vless|trojan|ss|hysteria2)://" | grep -v "0.0.0.0" >> vpn.json || true
          fi

          rm -f raw.txt

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add vpn.json
          git commit -m "Update" || exit 0
          git push origin main || git push --force
